### ISSUE TITLE
Android Click Event Firing

### ISSUE THREAD

**Issue by ravinderjangra** [shuklajay/CollapseListView-in-xamarin.forms#2]
In android, click event is firing repeatedly on single click when select only one child menu all the child are triggering automatically.

**Comment by shuklajay** [comment]
Ohh Fixed it check and let me know

**Comment by ravinderjangra** [comment]
Thanks. It's Working Fine.
Did you make nay change in ios too?

**Comment by shuklajay** [comment]
Nope ios is working fine you can give star to this repo if it is useful
