### ISSUE TITLE
Expanding item in large list makes list scroll up

### ISSUE THREAD

**Issue by LanzoVanSlooten** [shuklajay/CollapseListView-in-xamarin.forms#5]
I have changed your example so that the items list contains 12 items.  Only the first 10 items are shown.

Now I scroll down and expand the last item. The list goes up and the item I expanded is not visible anymore.

Do you have a solution for me.

![state after expanding and scroll down again](https://user-images.githubusercontent.com/34437652/45151895-d97d1500-b1cf-11e8-826b-3c05bc42b6de.png)
![start up screen](https://user-images.githubusercontent.com/34437652/45151896-d97d1500-b1cf-11e8-8e08-3fcd58c4c1c3.png)

**Comment by shuklajay** [comment]
This is expected because the CollapseListview measures its items by checking their RowHeight. For example when you dynamically change the Height of the ViewCell the Listview doesn't check if the ActualRowHeight for each row has changed.

Play with RowHeight in iOS renderer
